### ISSUE TITLE
Bug: tells that default stages are missing when no stages definition have been made

### ISSUE THREAD

**Issue by Quanalogy** [alesbrelih/gitlab-ci-ls#113]
As seen in the image below the default stages of build, test  and deploy are not understood by this LS:

![image](https://github.com/user-attachments/assets/8d2b2281-00b6-44f4-8d9b-9d358e0032da)

```yml
build:
  stage: build
  script:
    - echo "building..."

test:
  stage: test
  script:
    - echo "testing..."

deploy:
  stage: deploy
  script:
    - echo "deploying..."
```

Inserting the stages definition resolves the issue 

![image](https://github.com/user-attachments/assets/046dffb7-ceb3-4868-802e-53e6ec074155)

Code:

```yml
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "building..."

test:
  stage: test
  script:
    - echo "testing..."

deploy:
  stage: deploy
  script:
    - echo "deploying..."
```

but the errors from example  1 was of cause wrong.

My setup is: 

```bash
$ nvim --version
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
```

gitlab-ci-ls version 0.21.0
