### ISSUE TITLE
Issue with includes

### ISSUE THREAD

**Issue by lervag** [alesbrelih/gitlab-ci-ls#128]
I'm testing this tool right now. I have the following includes in my yaml:

```
include:
  - project: 'foo/cicd-helpers'
    file: '/helpers.yml'
  - project: 'bar/gitlab-ci-helpers'
    file: '/gitlab-ci-helpers.yml'
```

And I see this output in the log files:

```
[00:00:00.044] (1357946161c0) ERROR  error parsing yaml: include:
  - project: foo/cicd-helpers
    file: /helpers.yml
  - project: bar/gitlab-ci-helpers
    file: /gitlab-ci-helpers.yml, got err: include: data did not match any variant of untagged enum IncludeItem at line 2 column 3
```

Am I doing something wrong here, or is this perhaps a bug?

**Comment by alesbrelih** [comment]
Hey, this is definitely a but.
I think I know the problem. I don't think I have project reference set as optional.

I'll fix this, it shouldn't take long.

**Comment by lervag** [comment]
Cool, very glad to hear that.

> I don't think I have project reference set as optional.

What did you mean by this, i.e. "set as optional"?

**Comment by alesbrelih** [comment]
When I'm parsing yaml, I thought I expected that reference is always set.

Like:

```
project: something
ref: 1.0.0
file:
  - somefile
```

In your case you didn't set it. But it turned out that this isn't the problem. Problem is that I expected that **file** is an array.

So if you want to test functionality. Please change:

```
include:
  - project: 'foo/cicd-helpers'
    file: '/helpers.yml'
  - project: 'bar/gitlab-ci-helpers'
    file: '/gitlab-ci-helpers.yml'
```

To 

```
include:
  - project: 'foo/cicd-helpers'
    file: 
      - '/helpers.yml'
  - project: 'bar/gitlab-ci-helpers'
    file: 
      - '/gitlab-ci-helpers.yml'
```

This should work and allow you to test functionality. But yeah it's a bug and I'll try fix it asap
