### ISSUE TITLE
Definitions not found in included yml files

### ISSUE THREAD

**Issue by estk** [alesbrelih/gitlab-ci-ls#309]
In my repo I have the following layout, the language server complains that the `stage: sanity` does not exist and that the `.rust_base` does not exist.

.gitlab-ci.yml
```
include:
  - local: .gitlab/ci/templates/*.yml

stages:
  - sanity
  - unittest
  - build
```

.gitlab/ci/templates/00-templates.yml
```
.rust_base:
  image: ${RUST_DEBIAN_12_IMAGE}

```
.gitlab/ci/templates/01-sanity.yml
```
cargo_fmt:
  stage: sanity # Error: does not exist
  extends: .rust_base # Error: does not exist
  script:
    - cargo +nightly fmt -- --check
```
